POST http://localhost:5000/api/movies
Content-Type: application/json

{
    "title": "short circuit",
    "genreId": "5d48c3ee0e543c17c0650fba",
    "numberInStock": "90",
    "dailyRentalRate": "4.99"
}