PUT http://localhost:5000/api/movies/5d39f1101373e370c7bb090d
Content-Type: application/json

  {
    "title": "short circuit",
    "genreId": "5d38cbcf99e7d92b28a4c63d",
    "numberInStock": 45,
    "dailyRentalRate": 5
  }